apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rg64nluza-java-quarkus-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/rg64nluza-java-quarkus